### ISSUE TITLE
[Suggestion]: Config to limit how big a network can be

### ISSUE THREAD

**Issue by bangetto** [foxynotail/create-storage-mod-fabric#10]
I didn't saw any limit on how big storage networks can be, meaning they technically can be infinite, and I personally think that these network shouldn't be used for item transportation over longer distances, and at the moment the only option for me is to make storage trims and storage controllers stupidly expensive

**Comment by foxynotail** [comment]
This already exists. By default the range is 32 blocks from each controller. It can already be configured in the config.

**Comment by bangetto** [comment]
oh sorry, I'm all over the place
