### ISSUE TITLE
[Suggestion] Config to limit how many upgrades can be added to simple storage box

### ISSUE THREAD

**Issue by bangetto** [foxynotail/create-storage-mod-fabric#11]
32x2^9=16384=256 stacks , which I think is a bit too much for a single block to hold, and I want to lower it

> note: this was the one I wanted to open, I just all over the place

**Comment by bangetto** [comment]
for comparison a vault block by default can only hold 27 stacks, even though it is more expensive, plus you can't pick it up, or easily take in&out items easily, and they are big

**Comment by foxynotail** [comment]
This adds unnecessary complexity without improving the mod in any meaningful way. 
Players can limit the number of upgrades by simply putting less in. 
I cannot think of a reasonable situation where this would be useful. 
Adding roadblocks into gameplay that offer no substantial reward or interesting alternative is not good game / mod design.

**Comment by bangetto** [comment]
it would be really handy for modpack balancing, I want it to lower it, but other might want to make it higher to match their needs, it is the flexibility, that modpack devs don't have to balance every other storage block to make this mod into their own balancing system, instead they could play around this and give or take where is needed for a smooth experience

**Comment by adaliszk** [comment]
I will use this mod once I can configure the drawer sizes. I'm afraid I have to disagree with the current size; just look at the extended drawers that max out with 128 stacks and take a lot to get there with tiered upgrades. Here just make the upgrades cheaply and chuck in as much as you need.

I get that for responsible people, it's not a problem, but it causes major balancing issues in modpacks where you essentially dealing with kids who will abuse anything they can.
