### ISSUE TITLE
recipes are too cheap

### ISSUE THREAD

**Issue by bangetto** [foxynotail/create-storage-mod-fabric#8]
bc both the backpack and the storage box act like better shulker boxes they should include a shulker box/shell to make the end not completely useless and to avoid a minecart situation (when something is worst in every possible aspect)

**Comment by bangetto** [comment]
example for storage_box:
```json
{
  "type": "minecraft:crafting_shaped",
  "category": "misc",
  "group": "storage_box",
  "key": {
    "S": {
      "item": "minecraft:shulker_shell"
    },
    "C": {
      "item": "create:industrial_iron_block"
    },
    "V": {
      "item": "create:item_vault"
    },
    "D": {
      "item": "create:display_board"
    }
  },
  "pattern": [
    "CCC",
    "SVS",
    "CDC"
  ],
  "result": {
    "item": "fxntstorage:storage_box"
  },
  "show_notification": true
}

**Comment by foxynotail** [comment]
Compared to some other Storage Mods, I think these recipes are quite expensive and reasonable.
You can always modify the recipes yourself via a datapack, if you're not happy playing with the recipes in the mod.
